color = input("Enter a color: ")
plural_noun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity: ")
print("\n")
print("Roses are " + color.title())
print(plural_noun.title() + " are Blue")
print("I love " + celebrity.capitalize())
print("\n")